package hangmanguifinal;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author 349066522
 */
public class hangmangui extends javax.swing.JFrame {

    static String secret;
    static char guess;
    static int posGuess = 0;
    static int posAlpha = 0;
    static int posDash;
    static int numGuesses = 8;
    static boolean foundLetter = false;
    static String dash = "";
    static String alphabet = "abcdefghijklmnopqrstuvwxyz";
    
    /**
     * Creates new form hangmangui
     */
    public hangmangui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        guessesRemainingLabel = new javax.swing.JLabel();
        hideWordButtom = new javax.swing.JButton();
        guessButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        wordToGuessText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guessedLettersLabel = new javax.swing.JLabel();
        currentGuessText = new javax.swing.JTextField();
        alphabetLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        pictureContainer = new javax.swing.JLabel();
        respondToGuessLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(128, 128, 128));
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hangman!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Word to Guess:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Guessed Letters: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Current Guess:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Letters Remaining:");

        guessesRemainingLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guessesRemainingLabel.setText("8 guesses remaining");

        hideWordButtom.setText("Hide Word");
        hideWordButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideWordButtomActionPerformed(evt);
            }
        });

        guessButton.setText("Guess");
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        guessedLettersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        currentGuessText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGuessTextActionPerformed(evt);
            }
        });

        alphabetLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alphabetLabel.setText("abcdefghijklmnopqrstuvwxyz");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        respondToGuessLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        respondToGuessLabel.setText("Try Again!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wordToGuessText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(currentGuessText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(guessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(guessedLettersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(hideWordButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(guessesRemainingLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alphabetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 212, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(respondToGuessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pictureContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(wordToGuessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hideWordButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(guessedLettersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(currentGuessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(alphabetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(respondToGuessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessesRemainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pictureContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hideWordButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideWordButtomActionPerformed
        // TODO add your handling code here:
        
        currentGuessText.setText("");
        secret = String.valueOf(wordToGuessText.getText().toLowerCase());
        
        for(int i = 0; i < secret.length(); i++){
                dash = dash += "-";
            }
        
        alphabet = "abcdefghijklmnopqrstuvwxyz";
        alphabetLabel.setText(alphabet);
        wordToGuessText.setText("");
        guessesRemainingLabel.setText(numGuesses + " guesses remaining");
        guessedLettersLabel.setText(dash);
        currentGuessText.requestFocusInWindow();
 
    }//GEN-LAST:event_hideWordButtomActionPerformed

    private void currentGuessTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGuessTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGuessTextActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
        alphabet = "abcdefghijklmnopqrstuvwxyz";
        alphabetLabel.setText(alphabet);
        
        numGuesses = 8;
        
        guessesRemainingLabel.setText(numGuesses + " guesses remaining");
        
        currentGuessText.setText("");
        
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/blank.png")));
        
        respondToGuessLabel.setText("");
        
        wordToGuessText.setText("");
        wordToGuessText.requestFocusInWindow();
        
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        // TODO add your handling code here:
       
        
        do {
            
         // guess = char.valueOf(currentGuessText.getText().charAt(0));
            posGuess = 0;
            
            foundLetter = false;
            
            while(posGuess != -1){
                posGuess = secret.indexOf(guess, posGuess);
                
                if(posGuess !=-1){
                    dash = dash.substring(0, posGuess) + guess + dash.substring(posGuess + 1);
                    
                    posGuess++;
                    
                    foundLetter = true;
                }
                
                if(foundLetter == false){
                    numGuesses--;
                }
                
            }
            
            posAlpha = alphabet.indexOf(guess);
            
            if(posAlpha != -1){
                alphabet = alphabet.substring(0,posAlpha) + "/" + alphabet.substring(posAlpha+1);  
            }
            
            else {
                respondToGuessLabel.setText("You already guessed that letter!");
            }
            
            posDash = dash.indexOf("-");
            
            guessedLettersLabel.setText(dash);
            alphabetLabel.setText(alphabet);
            
            drawGallows(numGuesses);
            
            }while(posDash != -1 && numGuesses > 0);
        
        if(numGuesses == 0){
            respondToGuessLabel.setText("Hangman!");
            
        }
        
        else {
            respondToGuessLabel.setText("The Governor called! You're saved!");
        }
        
        respondToGuessLabel.setText("If you would like to play again, press the 'play again' button, if not, then click the 'exit' button");
        
        
    }//GEN-LAST:event_guessButtonActionPerformed

    private void drawGallows(int numGuesses) {// method to redraw gallows
      switch (numGuesses) {
        case 7:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows1.png")));
        break;
        case 6:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows2.png")));
        break;
        case 5:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows3.png")));
        break;
        case 4:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows4.png")));
        break;
        case 3:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows5.png")));
        break;
        case 2:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows6.png")));
        break;
        case 1:
        pictureContainer.setIcon(new javax.swing.ImageIcon(getClass().
            getResource("/my/gallows7.png")));
        break;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangmangui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangmangui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangmangui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangmangui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangmangui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alphabetLabel;
    private javax.swing.JTextField currentGuessText;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton guessButton;
    private javax.swing.JLabel guessedLettersLabel;
    private javax.swing.JLabel guessesRemainingLabel;
    private javax.swing.JButton hideWordButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel pictureContainer;
    private javax.swing.JLabel respondToGuessLabel;
    private javax.swing.JTextField wordToGuessText;
    // End of variables declaration//GEN-END:variables
}

